server:
  port: 8080

spring:
  application:
    name: "flights"
  datasource:
    url: jdbc:mysql://localhost:3306/travel_app
    username: root
    #password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
